language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        travis=1
        DATASTORE_HOST="http://localhost:8080"
        DATASTORE_DATASET="gcd-data"

# we have some dev dependencies to install, and we run some services needed for
# testing. Currently that's dynalite to emulate DynamoDB and gcd to emulate
# Google Cloud Datastore. We use supervisord to manage these processes, so see
# ./tests/start_ci_services.sh and ./tests/supervisord.ctl for details. Also
# note that we use the `sleep 5` hack below to give supervisord time to get
# the services started
sudo: false
install:
    - pip install --upgrade -r dev-requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --upgrade -r dev-requirements-27.txt; fi
    - ./tests/start_ci_services.sh
    - sleep 5

# command to run tests
script: nosetests

# Sometimes the services that we need to run are what fails... if that happens
# this may actually help us figure out what's going on
after_failure:
    - echo "***** supervisord log ****"
    - cat /tmp/supervisord.log
    - echo "***** dynalite stdout ****"
    - cat /tmp/dynalite_stdout.log
    - echo "***** dynalite stderr ****"
    - cat /tmp/dynalite_stderr.log
    - echo "***** gcd stdout ****"
    - cat /tmp/gcd_stdout.log
    - echo "***** gcd stderr ****"
    - cat /tmp/gcd_stderr.log
